server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 过期时间 30天(单位:秒)
    session:
      cookie:
        max-age: 2592000
spring:
  profiles:
    active: dev
  application:
    name: springboot-app
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB      # 单个文件的最大限制 (根据需求修改)
      max-request-size: 100MB   # 单次请求的总文件最大限制

minio:
  endpoint: http://xxx:9000  # MinIO 服务 API 地址 (注意是 API 端口，不能包含路径)
  accessKey: admin             # 访问密钥
  secretKey: Admin@123456             # 安全密钥
  bucketName: xiaoxiao             # 默认桶名称

session:
  token-expiration: 7200
  refresh-token-expiration: 604800